app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
#POSTS
class PostForm(FlaskForm):
	title = StringField('Title', validators=[DataRequired()])
	content = TextAreaField('Content', validators=[DataRequired()])
	submit = SubmitField('Post')

app/main/routes.py
from flask import render_template, request, Blueprint, redirect
from app.models import Post, Review, User
import json
import requests
#initlialize blueprint
main = Blueprint('main',__name__)


@main.route("/")
@main.route("/home")
def home():

	#PAGINATION
	page = request.args.get('page', 1, type = int)
	#most recent post tops
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page = page, per_page = 5)
	reviews = Review.query.order_by(Review.date_posted.desc()).paginate(page = page, per_page = 5)
	return render_template('home.html', posts=posts, reviews=reviews)


@main.route("/about")
def about():
	return render_template ('about.html', title='About')


@main.route("/quotes")
def quotes():
	random = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()
	return render_template('index.html', random=random)

app/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from app import db
from app.models import User, Post, Review
from app.posts.forms import PostForm

#instatntiating the blueprint
posts = Blueprint('posts',__name__)

#POSTS
@posts.route("/post/new", methods=['GET','POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title = form.title.data, content = form.content.data, user = current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your story has been posted, thank you', 'success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title = 'New Post', form = form, legend = 'New Story')


@posts.route("/post/<int:post_id>")
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title = post.title, post = post)


@posts.route("/post/<int:post_id>/update", methods=['GET','POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.user != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		post.title =  form.title.data
		post.content= form.content.data
		db.session.commit()
		flash('Story update successfull', 'success')
		return redirect(url_for('posts.post', post_id = post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title = 'Update  Story',
		form = form, legend = 'Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.user != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('OOps! Story deleted', 'danger')
	return redirect(url_for('main.home'))

app/reviews/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from app import db
from app.models import Review, User, Post
from app.reviews.forms import ReviewForm


#instatntiating the blueprint
reviews = Blueprint('reviews',__name__)

#POSTS
@reviews.route("/review/new/<int:id>", methods=['GET','POST'])
def new_review(id):
	form = ReviewForm()
	if form.validate_on_submit():
		review_id=id		
		user = User.query.filter_by(id = id).first_or_404()
		posts = Post.query.filter_by(user = user)\
		.order_by(Post.date_posted.desc())
		reviews = Review(name = form.name.data, content = form.content.data, user = current_user)
		db.session.add(reviews)
		db.session.commit()
		flash('thank you for contributing', 'success')
		return render_template('review.html', reviews = reviews, post_id=id)
	return render_template('create_review.html', title = 'New Review', form = form, id=id,legend = 'New Comment')


@reviews.route("/review/<int:post_id>")
def review(post_id):
	review = Review.query.get_or_404(post_id)
	return render_template('review.html', title = review.name, review = review)

#UPDATE REVIEW
@reviews.route("/review/<int:review_id>/update", methods=['GET','POST'])
@login_required
def update_review(review_id):
	review = Review.query.get_or_404(review_id)
	if review.user != current_user:
		abort(403)
	form = ReviewForm()
	if form.validate_on_submit():
		review.name =  form.name.data
		review.content= form.content.data
		db.session.commit()
		flash('Review update successfull', 'success')
		return redirect(url_for('reviews.review', review_id = id))
	elif request.method == 'GET':
		form.name.data = review.name
		form.content.data = review.content
	return render_template('create_review.html', title = 'Update Review',
		form = form, legend = 'Update Review')


#DELETE REVIEW
@reviews.route("/review/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_review(post_id):
	review = Review.query.get_or_404(post_id)
	if review.user != current_user:
		abort(403)
	db.session.delete(review)
	db.session.commit()
	flash('Contribution deleted', 'success')
	return redirect(url_for('main.home'))

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Post, Review
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from app.users.utils import save_picture, send_reset_email
from flask import session

#instatntiating the blueprint
users = Blueprint('users',__name__)

# @users.route('/my_url1')
# def my_view1():
#     data = None
#     if session.new:
#          user = User()
#          session['anonymous_user_id'] = user.id
#     else:
#          user = User.query.get(session['anonymous_user_id'])


@users.route("/register", methods=['GET','POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()

		def send_reset_email(user):
			token = user.get_reset_token()
			user_welcome = Message('User Welcome',
			sender = 'noreply@demo.com', recipients = [user.email] )
			user_welcome.body = '''Login;
			{url_for('main.login.html') }

			If yoy did not make this request, ignore this email and no changes will be made;

			'''
			mail.send(user_welcome)

		flash(f' {form.username.data}. Welcome to our community, You can now login', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title = 'Register', form = form)

@users.route("/login", methods=['GET','POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember = form.remember.data)
			next_page = request.args.get('next')
			#redirect to the next page if it exists, else render home
			#if there is not a next page, always render home
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash(f'Login Unsuccesfull. Kindly recheck email and password.', 'danger')
	return render_template('login.html', title = 'Login', form = form)


#LOGOUT USER
@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

	#ACCOUNT
@users.route("/account", methods=['GET','POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated, please login', 'success')
		return redirect (url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
		# form.bio.data = current_user.data
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('account.html', title = 'Account', 
		image_file = image_file, form=form)


#USERS TO SEE THEIR POSTS WHEN CLICK THEIR USERNAME
@users.route("/user/<string:username>")
def user_posts(username):
	#PAGINATION
	page = request.args.get('page', 1, type = int)
	user = User.query.filter_by(username = username).first_or_404()
	posts = Post.query.filter_by(user = user)\
		.order_by(Post.date_posted.desc())\
		.paginate(page = page, per_page = 5)
#add REVIEWS TO POSTS PAGE
	# reviews = Review.query.filter_by(user = user)\
	# 	.order_by(Review.date_posted.desc())
	return render_template('user_posts.html', posts=posts, user = user)


#USER REVIEWS
@users.route("/user/<string:post_id>")
def user_reviews(post_id):
	user = User.query.filter_by(username = username).first_or_404()
#ADD REVIEWS TO POSTS PAGE
	reviews = Review.query.filter_by(user = user)\
		.order_by(Review.date_posted.desc())
	return render_template('user_reviews.html',user = user, reviews = reviews)



@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent to your email account to help with password reset.', 'info')
		return redirect(url_for('main.login'))
	return render_template('reset_request.html', title = 'Request Password', form = form)


@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
	return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit() 
		flash(f'Password for {form.username.data} update susscessful. You can now login', 'success')
		return redirect(url_for('main.login'))
	return render_template('reset_token.html', title ='Reset Password', form = form)

app/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<h3 class="text-center">Your space</h3>
	<div style="box-sizing: border-box;">
		<p>
			They say, <strong><em>"have your space, ",</em> </strong> <br> we say;
			<strong><em>"love it, <br>hoping you'll: live it ;</em> </strong> <br>
			<hr>
			You're welcome to connect, rave, rant,.. yell, be you.. 
			<br>
			Let no one shassh you, 
			<br>
			we, @saferspace, got you a cooler space~
		</p>
		<div>
			<h3>
				Your blog lacks your “why”
			</h3>
			<p>How much energy are you expending on your blog? I don’t just mean writing, designing, optimizing SEO, or using social media.

				I mean how much of yourself are you putting into your blog?

				The power of your self, injected in your blog, can take you far. It’s about bringing forth your beliefs to the world and sharing your vision with people.

				And it all fuses together to create your “why”.
			</p>
		</div>
		<div>
			<p>Welcome to the Bloggers Pub</p>
		</div>
	</div>
{% endblock content %}

app/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
	<div class="media">
		<img width="90px" height="90px" class="rounded-circle sccount-img" src="{{ image_file }}">
		<div class="media-body">
			<h2 class="account-heading">{{ current_user.username }}</h2>
			<p class="text-secondary">{{current_user.email }} </p>
		</div>
	</div>
		<form method="POST", action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Account info</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
					{{ form.username(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
						<span>{{ error }} </span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.username(class="form-control form-control-lg") }} 
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}

					{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }} </span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.email(class="form-control form-control-lg") }} 
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.bio.label(class="form-control-label")}}

					{% if form.bio.errors %}
					{{ form.bio(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.bio.errors %}
						<span>{{ error }} </span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.bio(class="form-control form-control-lg") }} 
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label() }}
					{{ form.picture(class="form-control-file") }}

					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
						<span class="text-danger">{{ error }} </span> </br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
</div>
{% endblock content %}

app/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
	<form method="POST", action="">
		{{ form.hidden_tag()}}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">{{ legend }} </legend>
			<div class="form-group">
				{{ form.title.label(class="form-control-label")}}

				{% if form.title.errors %}
				{{ form.title(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.title.errors %}
					<span>{{ error }} </span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.title(class="form-control form-control-lg") }} 
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.content.label(class="form-control-label") }}

				{% if form.content.errors %}
				{{ form.content(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.content.errors %}
					<span>{{ error }} </span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.content(class="form-control form-control-lg") }} 
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info")}}
		</div>
	</form>
</div>
{% endblock content %}

app/templates/create_review.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
	<form method="POST", action="">
		{{ form.hidden_tag()}}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">{{ legend }} </legend>
			<div class="form-group">
				{{ form.name.label(class="form-control-label")}}

				{% if form.name.errors %}
				{{ form.name(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.name.errors %}
					<span>{{ error }} </span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.name(class="form-control form-control-lg") }} 
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.content.label(class="form-control-label") }}

				{% if form.content.errors %}
				{{ form.content(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.content.errors %}
					<span>{{ error }} </span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.content(class="form-control form-control-lg") }} 
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info")}}
		</div>
	</form>
</div>
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts.items %}

<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static',filename = 'profile_pics/' + post.user.image_file) }} ">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2" href="{{url_for('users.user_posts', username = post.user.username) }}">{{ post.user.username}}</a>
			<small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}} </small>
		</div>
		<h3><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }} ">{{post.title}} </a></h3>
		<p class="article-content">{{post.content}} </p>
	</div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge =1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
	{% if posts.page == page_num %}
	<a class="btn-info mb-4" href="{{url_for('main.home',page=page_num ) }} ">{{ page_num }}</a>
	{% else %}
	<a class="btn btn-outline-info mb-4" href="{{url_for('main.home',page=page_num ) }} ">{{ page_num }}</a>
	{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
	<p>Random Quotes</p>
	<p>{{random.quote}}</p>
</div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CDN and CSS section-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css') }} ">

	{% if title %}
		<title>@Care Hub{{title}} </title>
	{% else %}
		<title>@Care Hub</title>
	{% endif %}
</head>
<body class="container-fluid">
	<div style="padding-left: 8%; color: rgb(8, 117, 108;" class="">
		<h2 class="text-center">You're @Care Hub<br><span style="font-size: 12px; font-style: italic;">Grow and glow: thorns have roses;
		</span>
	</h2>
	</div>

	<header class="row">
		<nav style="margin-left: 30%" class="container navbar navbar-expand-md">
			<div style="color: black;">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="" >
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse">
					<div class="">
						<a class="mr-4 ml-4" href="{{ url_for('main.home') }}">Home</a>
						<a class="mr-4 ml-4" href="{{ url_for('main.about') }}">About</a>
					</div>
					<div style="box-sizing: border-box; display: inline-flex;">
						{% if current_user.is_authenticated %}
						<a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Post Story</a>
						<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
						<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
						{% else %}
						<div style="display: inline-flex; float: right;" class="ml-10">
							<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
							<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
						</div>


						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>
<main role="main">
	<div class="row">
		<div class="col-sm-3">
			<div class="content-section" style="font-size: 14px; font-style: italic;">
				<a href="{{url_for('main.quotes')}} ">
					<h3>Quote ~YouR~ DaY</h3>
				</a>
				<p class="text-muted">
					May be it's time we realized that, probably, <br>
					just by some cool chance,.. thorns have roses, <br> and not as per the normal convention,</b>
					 click the link above for more inspiration,<br> and see liberal challenges posed to the "norms".

				</p>
			</div>
		</div>
		<div class="col-sm-7" style="font-size: 14px; font-style: italic;">
			{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
			{% for category, message in messages %}
			<div class="alert alert-{{ category }}">
				{{ message }}
			</div>
			{% endfor %}
			{% endif %}
			{% endwith %}

			{% block content %} {% endblock %}
		</div>
		<div class="col-sm-2">
			<div class="content-section" style="font-size: 14px; font-style: italic;">
				<p class="text-muted">
					<ul style="">
						<a href="{{url_for('posts.new_post') }} ">
							<h5>Own a blog, Inspire;</h5>
						</a>
						<a href="{{url_for('posts.new_post') }} ">
							Click to get going
						</a>
					</ul>
				</p>
			</div>
		</div>
	</div>
	<footer style="font-size: 10px; outline-color: azure;" class="text-muted">
		<p class="text-center">Copyright (c) 2019 CareHub</p>
	</footer>
</main>
	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static',filename = 'profile_pics/' + post.user.image_file) }} ">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2 text-center" href="{{url_for('users.user_posts', username = post.user.username) }}">{{ post.user.username}}</a>
			<small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}} </small>
		</div>
		{% if post.user == current_user %}
		<div>
			<a class="btn, btn-warning btn-sm m-1" href="{{url_for('posts.update_post', post_id = post.id)}} " >Update</a>
			<button type="button" class="btn btn-danger btn-sm mt-1 mb-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
		</div>
		{% endif %}
		<h3 class="article-title text-center">{{post.title}} </a></h3>
		<p class="article-content">{{post.content}} </p>
		<p>
			<a class="btn, btn-sm btn-info btn-sm m-1" href="{{url_for('reviews.new_review', id = post.id)}} " >Comment on this post
			</a>
		</p>
</article>


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Delete Post ?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('posts.delete_post' , post_id = post.id) }} " method="POST">
					<input class="btn btn-danger" type="submit" value="Delete">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

app/templates/review.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2 text-center" href="">{{ reviews.name}}</a>
			<small class="text-muted">{{reviews.date_posted.strftime('%Y-%m-%d')}} </small>
		</div>
		{% if reviews.user == current_user %}
		<div>
			<!-- <a class="btn, btn-warning btn-sm m-1" href="{{url_for('reviews.update_review', review_id = reviews.id)}} " >Update</a>
			<button type="button" class="btn btn-danger btn-sm mt-1 mb-1" data-toggle="modal" data-target="#deleteModal">Delete</button> -->
		</div>
		{% endif %}
		<h3 class="article-title text-center">{{reviews.name}} </a></h3>
		<p class="article-content">{{reviews.content}} </p>
</article>

{% endblock content %}

app/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<h2 class="mb-3"> Posts by {{ user.username }} ({{ posts.total }} ) </h2>
{% for post in posts.items %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static',filename = 'profile_pics/' + post.user.image_file) }} ">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2 cutetext" href="{{url_for('users.user_posts', username = post.user.username) }} ">{{ post.user.username}}</a>
			<small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}} </small>
		</div>
		<h3><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }} ">{{post.title}} </a></h3>
		<p class="article-content">{{post.content}} </p>
	</div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge =1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
	{% if posts.page == page_num %}
	<a class="btn-info mb-4" href="{{url_for('users.user_posts', username = user.username, page=page_num ) }} ">{{ page_num }}</a>
	{% else %}
	<a class="btn btn-outline-info mb-4" href="{{url_for('users.user_posts', username = user.username, page=page_num ) }} ">{{ page_num }}</a>
	{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}

app/templates/user_reviews.html
{% extends "layout.html" %}
{% block content %}
<h2 class="mb-3">({{ reviews.total }} ) </h2>
{% for review in reviews.items %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static',filename = 'profile_pics/' + review.author.image_file) }} ">
	<div class="media-body">
		<div class="article-metadata">
			<a class="mr-2 cutetext" href="{{url_for('users.user_posts', username = review.author.username) }} ">{{ review.author.username}}</a>
			<small class="text-muted">{{review.date_posted.strftime('%Y-%m-%d')}} </small>
		</div>
		<h3><a class="article-title" href="{{ url_for('posts.review', post_id = review.id) }} ">{{review.title}} </a></h3>
		<p class="article-content">{{review.content}} </p>
	</div>
</article>
{% endfor %}
{% endblock content %}